import type { Metadata } from "next";
import { Hanken_Grotesk, Archivo } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/navigation/navbar";
import StudioHeaderPattern from "./components/artifacts/pattern";
import { FabMagnetic } from "./components/fab/Fab";
import { Stats } from "./components/hero-section/stats";

const hankenGrotesk = Hanken_Grotesk({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-hanken-grotesk",
});

const archivo = Archivo({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-archivo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hankenGrotesk.variable} ${archivo.variable} relative antialiased`}
      >
        <StudioHeaderPattern className="absolute top-0 left-0 size-full text-white" />
        <div className="//w-1/2 relative">
          <Navbar />
          {children}
        </div>
        {/* <Stats /> */}
      </body>
    </html>
  );
}
